---
# tasks file for loadbalancer


- name: installing haproxy software
  package:
       name: "haproxy"
       state: present

- name: copy file
  template:
       src: "/etc/haproxy/haproxy.cfg"
       dest: "/etc/haproxy/haproxy.cfg"
  notify: lb restart


- name: start lb
  service:
      name: "haproxy"
      state: started
